services:
  mtb-api:
    container_name: mtb_api
    image: anataarisa/mtb-aspnet:latest
    networks:
      mtb-api-networks:
    ports:
      - 8080:80
    environment:
      - ASPNETCORE_URLS=http://+:80
      - ConnectionStrings__DB=Server=${DB_HOST};uid=${DB_USERNAME};pwd=${DB_PASSWORD};database=${DB_NAME};TrustServerCertificate=True
      - JwtSettings__Key=${JWT_KEY}
      - JwtSettings__Issuer=${JWT_ISSUER}
      - JwtSettings__Audience=${JWT_AUDIENCE}
      - JwtSettings__DurationInDays=7
    restart: always

networks:
  mtb-api-networks:
    name: mtb_api_networks
    external: true